server:
   port: 8080 #tomcat启动端口
   tomcat:
      uri-encoding: UTF-8 #tomcat编码
   servlet:
      context-path: null
   naspath: D:\download
spring:
   servlet:
      multipart:
         max-file-size: 10MB # 最大支持文件大小 
         max-request-size: 50MB # 最大支持请求(总)大小
   datasource:
      url: jdbc:mysql://192.168.0.198:3306/test
      username: root
      password: 123456
      driver-class-name: org.mariadb.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
         minimum-idle: 3 #最小空闲数
         maximum-pool-size: 10
         auto-commit: true
         idle-timeout: 30000 #最大闲置时间
         max-lifetime: 1800000 #最大生命时间
         connection-timeout: 30000 #连接超时时间
         connection-test-query: SELECT 1
   cache:
      type: ehcache #指定缓存类型
      ehcache:
         config: classpath:ehcache.xml #缓存加载配置文件   
   thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      mode: HTML
      cache: false
   devtools:
      restart:
         enabled: false
mybatis:
   mapper-locations: classpath:/mapper/*.xml
   type-aliases-package: com.pp.entity
   configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl