server:
   port: 8080 #tomcat启动端口
   tomcat:
      uri-encoding: UTF-8 #tomcat编码
   servlet:
      context-path: null
   naspath: D:\download
spring:
   jackson:
      date-format: yyyy-MM-dd
      time-zone: GMT+8
   servlet:
      multipart:
         max-file-size: 10MB # 最大支持文件大小 
         max-request-size: 50MB # 最大支持请求(总)大小
   datasource:
      url: jdbc:mysql://10.7.135.12:3306/test
      username: root
      password: 123456
      driver-class-name: org.mariadb.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
         minimum-idle: 3 #最小空闲数
         maximum-pool-size: 10
         auto-commit: true
         idle-timeout: 30000 #最大闲置时间
         max-lifetime: 1800000 #最大生命时间
         connection-timeout: 30000 #连接超时时间
         connection-test-query: SELECT 1   
   thymeleaf:
      prefix: classpath:templates/
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      mode: HTML
      cache: false
   devtools:
      restart:
         enabled: false
   cache:
      type: redis #指定缓存类型  
      redis:
         time-to-live: 300000 #缓存超时时间ms
         cache-null-values: false #是否缓存空值
   redis:
      database: 0
      host: 10.7.135.12
      port: 6379
      password: 123456
      max-active: 200 #连接池最大连接数，负值表示没有限制
      max-wait: -1 #连接池最大阻塞等待时间，负值表示没有限制
      max-idle: 10 #连接池最大空闲连接
      min-idle: 0 #连接池最小空闲连接
      timeout: 1000 #连接超时
mybatis:
   mapper-locations: classpath:mapper/*.xml
   type-aliases-package: com.pp.entity
   configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl